import React from 'react'
// ... existing code ...
;
<h2 className="text-2xl font-semibold text-[#4075BF] mb-1">
    Experience with other tools?
  </h2>,
// ... existing code ...
// ... existing code ...
<h2 className="text-2xl font-semibold text-[#4075BF] mb-1">
      How do you want to be onboarded?
    </h2>;
// ... existing code ...