import React from 'react'
// ... existing code ...
;
<h2 className="text-2xl font-semibold text-[#4075BF] mb-1">
    Which best describes your role?
  </h2>,
// ... existing code ...
// ... existing code ...
<h2 className="text-2xl font-semibold text-[#4075BF] mt-8 mb-1">
      Who will be using SmarterQueue?
    </h2>;
// ... existing code ...